/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sourceFiles;


import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.table.DefaultTableModel;
import static sourceFiles.Utility.rs;
import static sourceFiles.Utility.*;
/**
 *
 * @author Khati
 */
public class BookMenus extends javax.swing.JFrame {

    /**
     * Creates new form BookMenus
     */
    private String FINAL_USERID;
private int FINAL_ACC_NO;

    public BookMenus() {
        initComponents();
        Utility.initialize();
        Utility.centreWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void switchToIssueBook(int acc_no)
    {
        TabbedPane.setSelectedIndex(1);
        accessionnoTF.setText(acc_no+"");
        searchDatabaseBTN.doClick();
        userIDTF.requestFocus();
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        TabbedPane = new javax.swing.JTabbedPane();
        SearchBookIF = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JTable();
        issueBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        modifyBtn = new javax.swing.JButton();
        bannerLbl = new javax.swing.JLabel();
        Separater = new javax.swing.JSeparator();
        genreLbl = new javax.swing.JLabel();
        genreCB = new javax.swing.JComboBox();
        goBtn = new javax.swing.JButton();
        IssueBookIF = new javax.swing.JInternalFrame();
        bannerLbl2 = new javax.swing.JLabel();
        separater = new javax.swing.JSeparator();
        accessionnoTF = new javax.swing.JTextField();
        accessionoLbl = new javax.swing.JLabel();
        searchDatabaseBTN = new javax.swing.JButton();
        bookDetailPanel = new javax.swing.JPanel();
        accessionNoStaticLbl = new javax.swing.JLabel();
        accessionNoLbl = new javax.swing.JLabel();
        nameStaticLbl = new javax.swing.JLabel();
        publisherStaticLbl = new javax.swing.JLabel();
        editionStaticLbl = new javax.swing.JLabel();
        bookNameLbl = new javax.swing.JLabel();
        publisherNameLbl = new javax.swing.JLabel();
        editionLbl1 = new javax.swing.JLabel();
        statusLbl1 = new javax.swing.JLabel();
        statusStaticLbl1 = new javax.swing.JLabel();
        issueBTN1 = new javax.swing.JButton();
        studentdetailPanel = new javax.swing.JPanel();
        userIDStaticLbl = new javax.swing.JLabel();
        userIDTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        daysStaticLbl = new javax.swing.JLabel();
        usernameStaticLbl = new javax.swing.JLabel();
        daysTF = new javax.swing.JTextField();
        phonenoStaticLbl = new javax.swing.JLabel();
        phoneNoTF = new javax.swing.JTextField();
        checkBTN = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        issueForStaticLbl = new javax.swing.JLabel();
        clearBTN = new javax.swing.JButton();
        exitBTN1 = new javax.swing.JButton();
        ReturnBookIF = new javax.swing.JInternalFrame();
        acnooTF = new javax.swing.JTextField();
        exitBTN2 = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        clearBTN2 = new javax.swing.JButton();
        accnoStaticLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bookdetailPnl = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        acL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nL = new javax.swing.JLabel();
        pL = new javax.swing.JLabel();
        yL = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pL1 = new javax.swing.JLabel();
        pL4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pL5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pL6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        submitBTN = new javax.swing.JButton();
        SelectBookIF = new javax.swing.JInternalFrame();
        publisherlbl = new javax.swing.JLabel();
        genreBannerLbl = new javax.swing.JLabel();
        accessionnoBannerLbl = new javax.swing.JLabel();
        genreLbl1 = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        bookList = new javax.swing.JList();
        editionBannerLbl = new javax.swing.JLabel();
        editionLbl = new javax.swing.JLabel();
        accessionnoLbl = new javax.swing.JLabel();
        statusLbl = new javax.swing.JLabel();
        bookTitleBannerLbl = new javax.swing.JLabel();
        statusBannerLbl = new javax.swing.JLabel();
        bookTitleLbl = new javax.swing.JLabel();
        exitBTN = new javax.swing.JButton();
        authorsBannerLbl = new javax.swing.JLabel();
        issueBTN = new javax.swing.JButton();
        authorsLbl = new javax.swing.JLabel();
        bannerLbl1 = new javax.swing.JLabel();
        publisherBannerLbl = new javax.swing.JLabel();
        alertLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        SearchBookIF.setTitle("Search Book");
        SearchBookIF.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addbook.png"))); // NOI18N
        SearchBookIF.setVisible(true);

        infoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Accessoin No", "Title", "Author(s)", "Publisher", "Edition", "Copies Left"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        infoTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                infoTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                infoTableFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(infoTable);

        issueBtn.setFont(new java.awt.Font("JasmineUPC", 1, 24)); // NOI18N
        issueBtn.setText("Issue Selected Book");
        issueBtn.setEnabled(false);
        issueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("JasmineUPC", 1, 30)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        modifyBtn.setFont(new java.awt.Font("JasmineUPC", 1, 24)); // NOI18N
        modifyBtn.setText("Modify Record");
        modifyBtn.setEnabled(false);
        modifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBtnActionPerformed(evt);
            }
        });

        bannerLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bannerLbl.setText("<html> <font size=6><b>Book Avalaible In Library</b></font><br>Select One Genre to Proceed");

        genreLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genreLbl.setText("Genre");

        genreCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computer Science", "Mathematics", "Mechanical", "Management", "Electronics", "Electrical", "Civil", "English Literature", "Magzines", "Hindi Literature", "Novel", "Biography", "Other" }));
        genreCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                genreCBMouseEntered(evt);
            }
        });
        genreCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreCBActionPerformed(evt);
            }
        });

        goBtn.setText("Go");
        goBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goBtnMouseExited(evt);
            }
        });
        goBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchBookIFLayout = new javax.swing.GroupLayout(SearchBookIF.getContentPane());
        SearchBookIF.getContentPane().setLayout(SearchBookIFLayout);
        SearchBookIFLayout.setHorizontalGroup(
            SearchBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBookIFLayout.createSequentialGroup()
                .addComponent(Separater, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SearchBookIFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SearchBookIFLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(genreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(genreCB, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(goBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchBookIFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(issueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        SearchBookIFLayout.setVerticalGroup(
            SearchBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchBookIFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separater, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SearchBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreCB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(SearchBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(modifyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TabbedPane.addTab("Search Book", new javax.swing.ImageIcon(getClass().getResource("/images/srchbook.png")), SearchBookIF); // NOI18N

        IssueBookIF.setTitle("Return Book");
        IssueBookIF.setVisible(true);

        bannerLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bannerLbl2.setText("<html> <font size =6><b>Book Issueing Form</b></font><br>Plz Fill Accesion No below then click search and Finally Click Issue");

        accessionnoTF.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        accessionnoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accessionnoTFKeyTyped(evt);
            }
        });

        accessionoLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        accessionoLbl.setText("Accession No");

        searchDatabaseBTN.setText("Search In Library Database ");
        searchDatabaseBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchDatabaseBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchDatabaseBTNMouseExited(evt);
            }
        });
        searchDatabaseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDatabaseBTNActionPerformed(evt);
            }
        });

        bookDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true), "Book Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        bookDetailPanel.setEnabled(false);

        accessionNoStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        accessionNoStaticLbl.setText("Accession No");

        accessionNoLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        accessionNoLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        nameStaticLbl.setText("Name");

        publisherStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        publisherStaticLbl.setText("Publ. Name");

        editionStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        editionStaticLbl.setText("Edition Year");

        bookNameLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        bookNameLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        publisherNameLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        publisherNameLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        editionLbl1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        editionLbl1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        statusLbl1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        statusLbl1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        statusStaticLbl1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        statusStaticLbl1.setText("Status ");

        javax.swing.GroupLayout bookDetailPanelLayout = new javax.swing.GroupLayout(bookDetailPanel);
        bookDetailPanel.setLayout(bookDetailPanelLayout);
        bookDetailPanelLayout.setHorizontalGroup(
            bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookDetailPanelLayout.createSequentialGroup()
                .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accessionNoStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publisherStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookDetailPanelLayout.createSequentialGroup()
                        .addComponent(accessionNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editionStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(editionLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookDetailPanelLayout.createSequentialGroup()
                        .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bookNameLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(publisherNameLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(statusStaticLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookDetailPanelLayout.setVerticalGroup(
            bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editionStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accessionNoStaticLbl)
                    .addComponent(accessionNoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(editionLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(publisherStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publisherNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusStaticLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        issueBTN1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        issueBTN1.setText("Issue");
        issueBTN1.setEnabled(false);
        issueBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBTN1ActionPerformed(evt);
            }
        });

        studentdetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true), "Please Fill the Detail For Issueing Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        studentdetailPanel.setEnabled(false);

        userIDStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        userIDStaticLbl.setText("User ID");

        userIDTF.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        userIDTF.setEnabled(false);

        nameTF.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        nameTF.setEnabled(false);

        daysStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        daysStaticLbl.setText("Days");

        usernameStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        usernameStaticLbl.setText("Name      :");

        daysTF.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        daysTF.setEnabled(false);

        phonenoStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        phonenoStaticLbl.setText("Phone no :");

        phoneNoTF.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        phoneNoTF.setEnabled(false);

        checkBTN.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        checkBTN.setText("Check");
        checkBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBTNActionPerformed(evt);
            }
        });

        issueForStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        issueForStaticLbl.setText("Issue For            :");

        javax.swing.GroupLayout studentdetailPanelLayout = new javax.swing.GroupLayout(studentdetailPanel);
        studentdetailPanel.setLayout(studentdetailPanelLayout);
        studentdetailPanelLayout.setHorizontalGroup(
            studentdetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentdetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentdetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentdetailPanelLayout.createSequentialGroup()
                        .addComponent(userIDStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(checkBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studentdetailPanelLayout.createSequentialGroup()
                        .addComponent(usernameStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(phonenoStaticLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phoneNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(studentdetailPanelLayout.createSequentialGroup()
                        .addComponent(issueForStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(daysTF, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(daysStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        studentdetailPanelLayout.setVerticalGroup(
            studentdetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentdetailPanelLayout.createSequentialGroup()
                .addGroup(studentdetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userIDStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(studentdetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(checkBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(studentdetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameStaticLbl)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenoStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentdetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daysStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daysTF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueForStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        clearBTN.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        clearBTN.setText("Clear");
        clearBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBTNMouseExited(evt);
            }
        });
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        exitBTN1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        exitBTN1.setText("Exit");
        exitBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBTN1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBTN1MouseExited(evt);
            }
        });
        exitBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IssueBookIFLayout = new javax.swing.GroupLayout(IssueBookIF.getContentPane());
        IssueBookIF.getContentPane().setLayout(IssueBookIFLayout);
        IssueBookIFLayout.setHorizontalGroup(
            IssueBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IssueBookIFLayout.createSequentialGroup()
                .addGroup(IssueBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IssueBookIFLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bannerLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IssueBookIFLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(separater, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IssueBookIFLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(accessionoLbl)
                        .addGap(18, 18, 18)
                        .addComponent(accessionnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(searchDatabaseBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IssueBookIFLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(IssueBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentdetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(IssueBookIFLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(exitBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(issueBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        IssueBookIFLayout.setVerticalGroup(
            IssueBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IssueBookIFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bannerLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separater, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IssueBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accessionoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accessionnoTF)
                    .addComponent(searchDatabaseBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentdetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IssueBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(196, 196, 196))
        );

        TabbedPane.addTab("Issue Book", new javax.swing.ImageIcon(getClass().getResource("/images/issuebook.png")), IssueBookIF); // NOI18N

        ReturnBookIF.setTitle("Return Book");
        ReturnBookIF.setVisible(true);

        acnooTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acnooTFFocusGained(evt);
            }
        });
        acnooTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                acnooTFKeyTyped(evt);
            }
        });

        exitBTN2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitBTN2.setText("Exit");
        exitBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTN2ActionPerformed(evt);
            }
        });

        searchBTN.setText("Search In Library Database ");
        searchBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBTNMouseExited(evt);
            }
        });
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        clearBTN2.setText("Clear");
        clearBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTN2ActionPerformed(evt);
            }
        });

        accnoStaticLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        accnoStaticLbl.setText("Accession No");

        bookdetailPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true), "Book Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        bookdetailPnl.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Accession No");

        acL.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Publ. Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Edition Year");

        nL.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pL.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        yL.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Issued To");

        pL1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pL4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 0, 51), null));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Return Date");

        pL5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Issuer ID");

        pL6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Issued Date");

        javax.swing.GroupLayout bookdetailPnlLayout = new javax.swing.GroupLayout(bookdetailPnl);
        bookdetailPnl.setLayout(bookdetailPnlLayout);
        bookdetailPnlLayout.setHorizontalGroup(
            bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookdetailPnlLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookdetailPnlLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pL6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookdetailPnlLayout.createSequentialGroup()
                        .addGroup(bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bookdetailPnlLayout.createSequentialGroup()
                                .addComponent(acL, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(yL, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nL, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)))
                    .addGroup(bookdetailPnlLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pL5, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bookdetailPnlLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pL4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        bookdetailPnlLayout.setVerticalGroup(
            bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookdetailPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(acL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(yL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pL1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pL5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pL6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookdetailPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pL4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("<html> <font size =5><b>PLz. Fill the Details for Submission of Book</b></font> ");

        submitBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submitBTN.setText("Submit");
        submitBTN.setEnabled(false);
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReturnBookIFLayout = new javax.swing.GroupLayout(ReturnBookIF.getContentPane());
        ReturnBookIF.getContentPane().setLayout(ReturnBookIFLayout);
        ReturnBookIFLayout.setHorizontalGroup(
            ReturnBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnBookIFLayout.createSequentialGroup()
                .addGroup(ReturnBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReturnBookIFLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(ReturnBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ReturnBookIFLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(accnoStaticLbl)
                                .addGap(11, 11, 11)
                                .addComponent(acnooTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ReturnBookIFLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(exitBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(clearBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReturnBookIFLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bookdetailPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ReturnBookIFLayout.setVerticalGroup(
            ReturnBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReturnBookIFLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(ReturnBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReturnBookIFLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(accnoStaticLbl))
                    .addGroup(ReturnBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acnooTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookdetailPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(ReturnBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        TabbedPane.addTab("Return Book", new javax.swing.ImageIcon(getClass().getResource("/images/subBook.png")), ReturnBookIF); // NOI18N

        SelectBookIF.setTitle("Select Book");
        SelectBookIF.setVisible(true);

        publisherlbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        genreBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        genreBannerLbl.setText("Genre");

        accessionnoBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        accessionnoBannerLbl.setText("Accession No.");

        genreLbl1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        bookList.setModel(new DefaultListModel());
        bookList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookListMouseClicked(evt);
            }
        });
        bookList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                bookListValueChanged(evt);
            }
        });
        ScrollPane.setViewportView(bookList);

        editionBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editionBannerLbl.setText("Year");

        editionLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        accessionnoLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        statusLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        bookTitleBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bookTitleBannerLbl.setText("Book Title");

        statusBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        statusBannerLbl.setText("Status");

        bookTitleLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        exitBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBTNMouseExited(evt);
            }
        });
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        authorsBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        authorsBannerLbl.setText("Authors");

        issueBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        issueBTN.setText("Issue");
        issueBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                issueBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                issueBTNMouseExited(evt);
            }
        });
        issueBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBTNActionPerformed(evt);
            }
        });

        authorsLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        bannerLbl1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bannerLbl1.setText("Select A Book From List.........");

        publisherBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        publisherBannerLbl.setText("Publisher");

        alertLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout SelectBookIFLayout = new javax.swing.GroupLayout(SelectBookIF.getContentPane());
        SelectBookIF.getContentPane().setLayout(SelectBookIFLayout);
        SelectBookIFLayout.setHorizontalGroup(
            SelectBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectBookIFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SelectBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectBookIFLayout.createSequentialGroup()
                        .addComponent(bannerLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(406, 406, 406))
                    .addGroup(SelectBookIFLayout.createSequentialGroup()
                        .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(SelectBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectBookIFLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                                .addComponent(alertLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))
                            .addGroup(SelectBookIFLayout.createSequentialGroup()
                                .addGroup(SelectBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SelectBookIFLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(SelectBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(editionBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(statusBannerLbl)
                                            .addComponent(genreBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(SelectBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(authorsBannerLbl)
                                                .addComponent(publisherBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(accessionnoBannerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                                .addComponent(bookTitleBannerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(29, 29, 29)
                                        .addGroup(SelectBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(accessionnoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bookTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(authorsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                                            .addComponent(publisherlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(editionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(genreLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(SelectBookIFLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(119, 119, 119)
                                        .addComponent(issueBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        SelectBookIFLayout.setVerticalGroup(
            SelectBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectBookIFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bannerLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(SelectBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectBookIFLayout.createSequentialGroup()
                        .addGroup(SelectBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectBookIFLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(accessionnoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(authorsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(SelectBookIFLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(accessionnoBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookTitleBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(authorsBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)))
                        .addGroup(SelectBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(publisherBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publisherlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(SelectBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectBookIFLayout.createSequentialGroup()
                                .addComponent(genreLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectBookIFLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(genreBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(editionBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alertLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SelectBookIFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(issueBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectBookIFLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        TabbedPane.addTab("Select Book", new javax.swing.ImageIcon(getClass().getResource("/images/modbook.png")), SelectBookIF); // NOI18N

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel4.setText("WestSide Library Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_infoTableFocusGained
        issueBtn.setEnabled(true);
        modifyBtn.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_infoTableFocusGained

    private void infoTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_infoTableFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_infoTableFocusLost

    private void issueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBtnActionPerformed
        int x = infoTable.getSelectedRow();
        Object val = infoTable.getValueAt(x,0);
        int value = Integer.parseInt(val.toString());
        switchToIssueBook(value);
   
    }//GEN-LAST:event_issueBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnActionPerformed

    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBtnActionPerformed
        int x = infoTable.getSelectedRow();
        Object val = infoTable.getValueAt(x,0);
      //  ModifyBookData ps = new ModifyBookData();
     //   ps.setVisible(true);
      //  ps.setData(val);// TODO add your handling code here:
    }//GEN-LAST:event_modifyBtnActionPerformed

    private void genreCBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genreCBMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_genreCBMouseEntered

    private void genreCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreCBActionPerformed

    private void goBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_goBtnMouseEntered

    private void goBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_goBtnMouseExited

    private void goBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBtnActionPerformed
        DefaultTableModel model =(DefaultTableModel)infoTable.getModel();
        try{
            String genre = (String) genreCB.getSelectedItem();
            String query="SELECT DISTINCT A.Acc_No,A.Title,A.Author1,A.Author2,A.Author3,B.Pub_name,A.Edition,(SELECT count(Acc_NO) FROM book_rec where Genre='"+genre+"' and Status='Unissued') AS Copies_Left From book_rec A,publisher B where Genre='"+genre+"' and A.pub_ID=B.pub_ID Order by Title asc;";
            rs =Utility.stmt.executeQuery(query);
            int x =infoTable.getRowCount();
            int p=0;
            for(;x>p;++p)
            {
                model.removeRow(0);
            }
            while(rs.next())
            {
                int accessionNo =rs.getInt("Acc_No");
                String title =rs.getString("Title");
                String authors =rs.getString("Author1").concat(" , ").concat(rs.getString("Author2")).concat(" , ").concat(rs.getString("Author3"));
                String publisher =rs.getString("Pub_Name");
                String copies=rs.getString("Copies_Left");
                String edition =rs.getString("Edition");
                model.addRow(new Object[] {accessionNo,title,authors,publisher,edition,copies});
            }
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog (this, e.getMessage());
        }
    }//GEN-LAST:event_goBtnActionPerformed

    private void bookListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookListMouseClicked
        String value=(String)bookList.getSelectedValue();
        try
        {
            String query ="SELECT A.Acc_No,A.Title,A.Author1,A.Author2,A.Author3,B.Pub_name,A.genre,A.Edition,A.status,(SELECT count(Acc_NO) FROM book_rec where Title='"+value+"' and Status='Unissued') AS Copies_Left From book_rec A,publisher B where Title='"+value+"' and A.pub_ID=B.pub_ID Order by Title asc;";
            rs=Utility.stmt.executeQuery(query);
            while(rs.next())
            {
                int accessionNo = rs.getInt("Acc_No");
                String title  = rs.getString("Title");
                String authors ="<html>" + rs.getString("Author1").concat(" <br> ").concat(rs.getString("Author2")).concat(" <br> ").concat(rs.getString("Author3"));
                String publisher  = rs.getString("pub_name");
                String genre  = rs.getString("Genre");
                String edition  = rs.getString("Edition");
                String status = rs.getString("Copies_Left");
                accessionnoLbl.setText(accessionNo+"");
                authorsLbl.setText(authors);
                bookTitleLbl.setText(title);
                publisherlbl.setText(publisher);
                genreLbl1.setText("<html>"+genre);
                editionLbl.setText(edition);
                if(status.equals("0"))
                {
                    statusLbl.setText("No Copy Left");
                }
                else
                statusLbl.setText(status + " Copies Left");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        alertLbl.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_bookListMouseClicked

    private void bookListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_bookListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_bookListValueChanged

    private void exitBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTNMouseEntered

    private void exitBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTNMouseExited

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTNActionPerformed

    private void issueBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_issueBTNMouseEntered

    private void issueBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_issueBTNMouseExited

    private void issueBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBTNActionPerformed
      
        try {
             if(statusLbl.getText().equals("No Copy Left"))
      {
           alertLbl.setText("<html> <font color=RED>No Copy of this Book is Avlaible  ..Choose some other Book </font>");
       }
       else
       {

           int temp =Integer.parseInt(accessionnoLbl.getText());
            switchToIssueBook(temp);
        }
        } catch (Exception ex) {
            Logger.getLogger(BookMenus.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_issueBTNActionPerformed

    private void accessionnoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accessionnoTFKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_accessionnoTFKeyTyped

    private void searchDatabaseBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchDatabaseBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDatabaseBTNMouseEntered

    private void searchDatabaseBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchDatabaseBTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDatabaseBTNMouseExited

    private void searchDatabaseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDatabaseBTNActionPerformed
        try{
            String query="SELECT A.Acc_no,A.Title,A.Edition,A.status,B.pub_name FROM book_rec A,Publisher B WHERE A.pub_ID=B.pub_ID AND A.Acc_no ="+accessionnoTF.getText()+";";
            rs =Utility.stmt.executeQuery(query);
            rs.first();
            accessionNoLbl.setText(rs.getInt("Acc_No")+"");
            editionLbl.setText(rs.getString("edition"));
            bookNameLbl.setText(rs.getString("Title"));
            publisherNameLbl.setText(rs.getString("Pub_name"));
            statusLbl.setText(rs.getString("Status"));

            if(statusLbl.getText().equals("Issued"))
            {
                JOptionPane.showMessageDialog(this,"Oops !!! Book is not left For Issueing");
                statusLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 51, 51), null));
            }
            else
            {
                statusLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 255, 0), null));
                userIDTF.setEnabled(true);
                userIDTF.requestFocus();
            }}
            catch(Exception ep)
            {
                JOptionPane.showMessageDialog (this,ep.getMessage()/*"The Accession No you entered is not valid"*/);
            }

            // TODO add your handling code here:
    }//GEN-LAST:event_searchDatabaseBTNActionPerformed

    private void issueBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBTN1ActionPerformed
        try{
            if(new Utility().validatePassword(FINAL_USERID))
            {
                String query,query2;
                String returnDate = Utility.getReturnDate(Integer.parseInt(daysTF.getText()));
                query="insert into issued_books Values("+FINAL_ACC_NO+",'"+FINAL_USERID+"','"+Utility.getCurrentDate()+"','"+returnDate+"');";
                query2="UPDATE book_rec SET status='Issued' WHERE Acc_No="+FINAL_ACC_NO+";";
                Utility.stmt.executeUpdate(query);
                Utility.stmt.executeUpdate(query2);
                JOptionPane.showMessageDialog(this,"Congrats !! Your Book has been Issued","Success",JOptionPane.INFORMATION_MESSAGE);
                clearBTN.doClick();
                accessionnoTF.requestFocus();
            }
            else
            JOptionPane.showMessageDialog(this,"The password you entered is Invalid","Wrong password",ERROR_MESSAGE);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_issueBTN1ActionPerformed

    private void checkBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBTNActionPerformed
        String query = "Select * from user where user_Id='"+userIDTF.getText()+"';";
        try
        {
            rs = Utility.stmt.executeQuery(query);
            rs.first();
            nameTF.setText(rs.getString("User_Name"));
            phoneNoTF.setText(rs.getString("User_Phoneno"));
            daysTF.setEnabled(true);
            daysTF.requestFocus();
            issueBTN.setEnabled(true);
            FINAL_USERID = userIDTF.getText();
            FINAL_ACC_NO = Integer.parseInt(accessionNoLbl.getText());
        }
        catch(SQLException e)
        {
            userIDTF.setText(null);
            userIDTF.requestFocus();
            JOptionPane.showMessageDialog(this,"The User ID does not exist","Error",JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_checkBTNActionPerformed

    private void clearBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBTNMouseEntered

    private void clearBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBTNMouseExited

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        accessionnoTF.setText(null);
        bookNameLbl.setText(null);
        publisherNameLbl.setText(null);
        statusLbl.setText(null);
        accessionNoLbl.setText(null);
        editionLbl.setText(null);
        issueBTN.setEnabled(false);
        
        daysTF.setText(null);
        userIDTF.setText(null);
        nameTF.setText(null);
        phoneNoTF.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBTNActionPerformed

    private void exitBTN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTN1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTN1MouseEntered

    private void exitBTN1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTN1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTN1MouseExited

    private void exitBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTN1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTN1ActionPerformed

    private void acnooTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acnooTFFocusGained
               // TODO add your handling code here:
    }//GEN-LAST:event_acnooTFFocusGained

    private void acnooTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acnooTFKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_acnooTFKeyTyped

    private void exitBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTN2ActionPerformed
        dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_exitBTN2ActionPerformed

    private void searchBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBTNMouseEntered

    private void searchBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBTNMouseExited

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
//        try {
//            int x = Integer.parseInt(AcNoTF.getText());
//            try {
//                String query;
//                String tag = AcNoTF.getText();
//                
//                System.out.print(query);
//                ResultSet rs = Utility.stmt.executeQuery(query);
//                while (rs.next()) {
//                    acL.setText(rs.getInt("Ac_No") + "");
//                    yL.setText(rs.getInt("year") + "");
//                    nL.setText(rs.getString("Title"));
//                    pL.setText(rs.getString("Publisher"));
//                    pL1.setText(rs.getString("Isr_Name"));
//                    pL5.setText(rs.getString("Isrtc_Degs"));
//                    pL2.setText(rs.getString("St_cls"));
//                    pL3.setText(rs.getString("St_sec"));
//                    pL4.setText(rs.getString("Is_on"));
//
//                }
//                if(pL1.getText().isEmpty()) {
//
//                } else {
//                    jButton2.setEnabled(true);
//                }
//
//            } catch (Exception ep) {
//
//                JOptionPane.showMessageDialog(this,ep.getMessage());
//            }
//        } catch (Exception e) {
//            eL.setText("The Accession No you entered doesn't seems to be Right");
//
//        } // TODO add your handling code here:
    }//GEN-LAST:event_searchBTNActionPerformed

    private void clearBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTN2ActionPerformed
//        //AcNoTF.setText(null);
//        nL.setText(null);
//        pL.setText(null);
//        pL1.setText(null);
//        pL2.setText(null);
//        pL3.setText(null);
//        pL4.setText(null);
//        acL.setText(null);
//        yL.setText(null);
//        jButton2.setEnabled(false);
//        eL.setText(null);
//        cTF.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_clearBTN2ActionPerformed

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
//        JOptionPane.show
//
//        int ac = Integer.parseInt(acL.getText());
//        try{
//            String query="Update book_rec set Copies_issued = Copies_issued -1 Where Ac_No="+acL.getText()+";";
//            String qry2="Delete from issuer_details where Ac_No="+acL.getText()+" AND Is_on='"+pL4.getText()+"';";
//            Utility.stmt.executeUpdate(query);
//            Utility.stmt.executeUpdate(qry2);
//
//            JOptionPane.showMessageDialog (null,"Book Submitted");
//            dispose();
//
//        }
//        catch (Exception e) {
//            JOptionPane.showMessageDialog (null,e.getMessage());
//        }
    }//GEN-LAST:event_submitBTNActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
DefaultListModel list = (DefaultListModel) bookList.getModel();
        try
{
      String query ="SELECT DISTINCT Title From book_rec Order By Title desc;";
       rs=Utility.stmt.executeQuery(query);
       while(rs.next())
       {
       String tit  = rs.getString("Title");
       list.add(0,tit);
       bookList.setModel(list);
       }
}
catch (Exception e)
     {
       JOptionPane.showMessageDialog(this, e.getMessage());
     }        // TODO add your handling code here:
                                            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookMenus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame IssueBookIF;
    private javax.swing.JInternalFrame ReturnBookIF;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JInternalFrame SearchBookIF;
    private javax.swing.JInternalFrame SelectBookIF;
    private javax.swing.JSeparator Separater;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JLabel acL;
    private javax.swing.JLabel accessionNoLbl;
    private javax.swing.JLabel accessionNoStaticLbl;
    private javax.swing.JLabel accessionnoBannerLbl;
    private javax.swing.JLabel accessionnoLbl;
    private javax.swing.JTextField accessionnoTF;
    private javax.swing.JLabel accessionoLbl;
    private javax.swing.JLabel accnoStaticLbl;
    private javax.swing.JTextField acnooTF;
    private javax.swing.JLabel alertLbl;
    private javax.swing.JLabel authorsBannerLbl;
    private javax.swing.JLabel authorsLbl;
    private javax.swing.JLabel bannerLbl;
    private javax.swing.JLabel bannerLbl1;
    private javax.swing.JLabel bannerLbl2;
    private javax.swing.JPanel bookDetailPanel;
    private javax.swing.JList bookList;
    private javax.swing.JLabel bookNameLbl;
    private javax.swing.JLabel bookTitleBannerLbl;
    private javax.swing.JLabel bookTitleLbl;
    private javax.swing.JPanel bookdetailPnl;
    private javax.swing.JButton checkBTN;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton clearBTN2;
    private javax.swing.JLabel daysStaticLbl;
    private javax.swing.JTextField daysTF;
    private javax.swing.JLabel editionBannerLbl;
    private javax.swing.JLabel editionLbl;
    private javax.swing.JLabel editionLbl1;
    private javax.swing.JLabel editionStaticLbl;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton exitBTN1;
    private javax.swing.JButton exitBTN2;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel genreBannerLbl;
    private javax.swing.JComboBox genreCB;
    private javax.swing.JLabel genreLbl;
    private javax.swing.JLabel genreLbl1;
    private javax.swing.JButton goBtn;
    private javax.swing.JTable infoTable;
    private javax.swing.JButton issueBTN;
    private javax.swing.JButton issueBTN1;
    private javax.swing.JButton issueBtn;
    private javax.swing.JLabel issueForStaticLbl;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton modifyBtn;
    private javax.swing.JLabel nL;
    private javax.swing.JLabel nameStaticLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel pL;
    private javax.swing.JLabel pL1;
    private javax.swing.JLabel pL4;
    private javax.swing.JLabel pL5;
    private javax.swing.JLabel pL6;
    private javax.swing.JTextField phoneNoTF;
    private javax.swing.JLabel phonenoStaticLbl;
    private javax.swing.JLabel publisherBannerLbl;
    private javax.swing.JLabel publisherNameLbl;
    private javax.swing.JLabel publisherStaticLbl;
    private javax.swing.JLabel publisherlbl;
    private javax.swing.JButton searchBTN;
    private javax.swing.JButton searchDatabaseBTN;
    private javax.swing.JSeparator separater;
    private javax.swing.JLabel statusBannerLbl;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JLabel statusLbl1;
    private javax.swing.JLabel statusStaticLbl1;
    private javax.swing.JPanel studentdetailPanel;
    private javax.swing.JButton submitBTN;
    private javax.swing.JLabel userIDStaticLbl;
    private javax.swing.JTextField userIDTF;
    private javax.swing.JLabel usernameStaticLbl;
    private javax.swing.JLabel yL;
    // End of variables declaration//GEN-END:variables
}
