/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sourceFiles;

import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static sourceFiles.Utility.rs;
import static sourceFiles.Utility.stmt;

/**
 *
 * @author Khati
 */
public class BookManipulation extends javax.swing.JFrame {

    /**
     * Creates new form BookManipulation
     */
    String publisherID,publisherCity,publisherCountry;
    long publisherContactNo;
    boolean idAlreayPresent;
    public BookManipulation() {
        initComponents();
        Utility.centreWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        clearBTN = new javax.swing.JButton();
        componentPanel = new javax.swing.JPanel();
        accessionnoLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        editionLbl = new javax.swing.JLabel();
        genreLbl = new javax.swing.JLabel();
        genreCB = new javax.swing.JComboBox();
        accessionnoTF = new javax.swing.JTextField();
        editionTF = new javax.swing.JTextField();
        titleTF = new javax.swing.JTextField();
        publisherNameLbl = new javax.swing.JLabel();
        pagesTF = new javax.swing.JTextField();
        pagesLbl = new javax.swing.JLabel();
        publisherCityTF = new javax.swing.JTextField();
        publisherCityLbl = new javax.swing.JLabel();
        publisherCountryTF = new javax.swing.JTextField();
        publisherCountryLbl = new javax.swing.JLabel();
        publisherPhoneNoLbl = new javax.swing.JLabel();
        publisherPhoneNoTF = new javax.swing.JTextField();
        publisherNameTF = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        authorName1TF = new javax.swing.JTextField();
        authorName2TF = new javax.swing.JTextField();
        authorName3TF = new javax.swing.JTextField();
        authorLbl = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        priceLbl = new javax.swing.JLabel();
        bannerLBL = new javax.swing.JLabel();
        addBookBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        errorLabel = new javax.swing.JLabel();
        deleteBTN = new javax.swing.JButton();
        bannerStaticLbl = new javax.swing.JLabel();
        accessionnoTF1 = new javax.swing.JTextField();
        exitBTN1 = new javax.swing.JButton();
        bookDetailPanel = new javax.swing.JPanel();
        accessionnoStaticLabel = new javax.swing.JLabel();
        accessionnoLbl1 = new javax.swing.JLabel();
        nameStaticLbl = new javax.swing.JLabel();
        publishernameStaticLbl = new javax.swing.JLabel();
        editionStaticLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        publishernameLbl = new javax.swing.JLabel();
        editionLbl1 = new javax.swing.JLabel();
        accessionoStaticLbl = new javax.swing.JLabel();
        searchBTN = new javax.swing.JButton();
        newDefPanel = new javax.swing.JPanel();
        titleStaticLbl = new javax.swing.JLabel();
        publisherStaticLbl = new javax.swing.JLabel();
        editonStaticKbl = new javax.swing.JLabel();
        genreStaticLbl = new javax.swing.JLabel();
        pagesStaticLbl = new javax.swing.JLabel();
        genreCB1 = new javax.swing.JComboBox();
        newtitleTF = new javax.swing.JTextField();
        publisherTF = new javax.swing.JTextField();
        pagesTF1 = new javax.swing.JTextField();
        editionTF1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        authorName1TF1 = new javax.swing.JTextField();
        authorName2TF1 = new javax.swing.JTextField();
        authorName3TF1 = new javax.swing.JTextField();
        authorLbl1 = new javax.swing.JLabel();
        modifyBTN = new javax.swing.JButton();
        clearBTN1 = new javax.swing.JButton();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        ScrollPane = new javax.swing.JScrollPane();
        bookList = new javax.swing.JList();
        statusLbl = new javax.swing.JLabel();
        editionLbl2 = new javax.swing.JLabel();
        genreLbl1 = new javax.swing.JLabel();
        publisherlbl = new javax.swing.JLabel();
        authorsLbl = new javax.swing.JLabel();
        bookTitleLbl = new javax.swing.JLabel();
        accessionnoLbl2 = new javax.swing.JLabel();
        accessionnoBannerLbl = new javax.swing.JLabel();
        bookTitleBannerLbl = new javax.swing.JLabel();
        authorsBannerLbl = new javax.swing.JLabel();
        publisherBannerLbl = new javax.swing.JLabel();
        genreBannerLbl = new javax.swing.JLabel();
        editionBannerLbl = new javax.swing.JLabel();
        statusBannerLbl = new javax.swing.JLabel();
        issueBTN = new javax.swing.JButton();
        exitBTN2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Manipulation");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel4.setText("WestSide Library Management System");

        jInternalFrame1.setTitle("Add Book");
        jInternalFrame1.setVisible(true);

        clearBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clearBTN.setText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        componentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 2, true), "Add the Detail of New Book Here", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        accessionnoLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        accessionnoLbl.setText("Accession No");

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titleLbl.setText("Title");

        editionLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editionLbl.setText("Edition Year");

        genreLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        genreLbl.setText("Genre");

        genreCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computer Science", "Mathematics", "Mechanical", "Management", "Electronics", "Electrical", "Civil", "English Literature", "Magzines", "Hindi Literature", "Novel", "Biography", "Other" }));
        genreCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                genreCBMouseEntered(evt);
            }
        });
        genreCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreCBActionPerformed(evt);
            }
        });

        accessionnoTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                accessionnoTFFocusLost(evt);
            }
        });
        accessionnoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accessionnoTFKeyTyped(evt);
            }
        });

        editionTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editionTFKeyTyped(evt);
            }
        });

        titleTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                titleTFKeyTyped(evt);
            }
        });

        publisherNameLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        publisherNameLbl.setText("Publ. Name");

        pagesTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pagesTFKeyTyped(evt);
            }
        });

        pagesLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pagesLbl.setText("Pages");

        publisherCityTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                publisherCityTFKeyTyped(evt);
            }
        });

        publisherCityLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        publisherCityLbl.setText("Publ. City");

        publisherCountryTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                publisherCountryTFKeyTyped(evt);
            }
        });

        publisherCountryLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        publisherCountryLbl.setText("Publ. County");

        publisherPhoneNoLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        publisherPhoneNoLbl.setText("Publ. Phone No");

        publisherPhoneNoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                publisherPhoneNoTFKeyTyped(evt);
            }
        });

        publisherNameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                publisherNameTFFocusLost(evt);
            }
        });
        publisherNameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                publisherNameTFKeyTyped(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        authorName1TF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                authorName1TFFocusLost(evt);
            }
        });
        authorName1TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                authorName1TFKeyTyped(evt);
            }
        });

        authorName2TF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                authorName2TFFocusLost(evt);
            }
        });
        authorName2TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                authorName2TFKeyTyped(evt);
            }
        });

        authorName3TF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                authorName3TFFocusLost(evt);
            }
        });
        authorName3TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                authorName3TFKeyTyped(evt);
            }
        });

        authorLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        authorLbl.setText("Author(s)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(authorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorName3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorName2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorName1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorName1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorName2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorName3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        priceTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                priceTFKeyTyped(evt);
            }
        });

        priceLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        priceLbl.setText("Price");

        javax.swing.GroupLayout componentPanelLayout = new javax.swing.GroupLayout(componentPanel);
        componentPanel.setLayout(componentPanelLayout);
        componentPanelLayout.setHorizontalGroup(
            componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentPanelLayout.createSequentialGroup()
                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(componentPanelLayout.createSequentialGroup()
                        .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accessionnoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accessionnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(componentPanelLayout.createSequentialGroup()
                        .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(publisherCityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publisherNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(publisherNameTF)
                            .addComponent(publisherCityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(publisherCountryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editionLbl)
                    .addComponent(genreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publisherPhoneNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, componentPanelLayout.createSequentialGroup()
                        .addComponent(priceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(componentPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genreCB, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(componentPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(publisherCountryTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(componentPanelLayout.createSequentialGroup()
                                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pagesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(publisherPhoneNoTF, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(15, 15, 15))
        );
        componentPanelLayout.setVerticalGroup(
            componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(componentPanelLayout.createSequentialGroup()
                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, componentPanelLayout.createSequentialGroup()
                        .addComponent(accessionnoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(componentPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(editionLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(editionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(genreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genreCB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pagesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pagesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(priceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(publisherPhoneNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(publisherPhoneNoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(publisherCountryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(publisherCountryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(componentPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(publisherNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(publisherNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(componentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(publisherCityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(componentPanelLayout.createSequentialGroup()
                                        .addComponent(publisherCityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, componentPanelLayout.createSequentialGroup()
                        .addComponent(accessionnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );

        bannerLBL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bannerLBL.setText("<html> <font size =6><b>Add New Book To Library Database</b></font>");

        addBookBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addBookBTN.setText("Add Book To Library");
        addBookBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookBTNActionPerformed(evt);
            }
        });

        exitBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBookBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bannerLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(componentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(bannerLBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(componentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBookBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Add Book", new javax.swing.ImageIcon(getClass().getResource("/images/addbook.png")), jInternalFrame1); // NOI18N

        jInternalFrame2.setTitle("Modify Book");
        jInternalFrame2.setVisible(true);

        deleteBTN.setFont(new java.awt.Font("JasmineUPC", 1, 24)); // NOI18N
        deleteBTN.setText("Delete Book");
        deleteBTN.setEnabled(false);
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        bannerStaticLbl.setForeground(new java.awt.Color(51, 51, 51));
        bannerStaticLbl.setText("<html> <font size =5><b>Data Modification Form</b></font><br> Enter the Acc. No of Book");

        accessionnoTF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accessionnoTF1KeyTyped(evt);
            }
        });

        exitBTN1.setFont(new java.awt.Font("JasmineUPC", 1, 24)); // NOI18N
        exitBTN1.setText("Exit");
        exitBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTN1ActionPerformed(evt);
            }
        });

        bookDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true), "Book Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        bookDetailPanel.setEnabled(false);

        accessionnoStaticLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        accessionnoStaticLabel.setText("Accession No");

        accessionnoLbl1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameStaticLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameStaticLbl.setText("Name");

        publishernameStaticLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        publishernameStaticLbl.setText("Publ. Name");

        editionStaticLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editionStaticLbl.setText("Edition Year");

        nameLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        publishernameLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        editionLbl1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout bookDetailPanelLayout = new javax.swing.GroupLayout(bookDetailPanel);
        bookDetailPanel.setLayout(bookDetailPanelLayout);
        bookDetailPanelLayout.setHorizontalGroup(
            bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookDetailPanelLayout.createSequentialGroup()
                .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookDetailPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(nameStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookDetailPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(accessionnoStaticLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookDetailPanelLayout.createSequentialGroup()
                        .addComponent(accessionnoLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(editionStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookDetailPanelLayout.createSequentialGroup()
                        .addComponent(publishernameStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(publishernameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addComponent(editionLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );
        bookDetailPanelLayout.setVerticalGroup(
            bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accessionnoStaticLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accessionnoLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(editionStaticLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addComponent(editionLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookDetailPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(bookDetailPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(bookDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(publishernameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publishernameStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        accessionoStaticLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        accessionoStaticLbl.setText("Accession No");

        searchBTN.setText("Search In Library Database ");
        searchBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBTNMouseExited(evt);
            }
        });
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        newDefPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true), "New Definations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N

        titleStaticLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titleStaticLbl.setText("Title");

        publisherStaticLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        publisherStaticLbl.setText("Publisher");

        editonStaticKbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editonStaticKbl.setText("Year");

        genreStaticLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        genreStaticLbl.setText("Genre");

        pagesStaticLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pagesStaticLbl.setText("Pages");

        genreCB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Computer Science", "Mathematics", "Mechanical", "Management", "Electronics", "Electrical", "Civil", "English Literature", "Magzines", "Hindi Literature", "Novel", "Biography", "Other" }));
        genreCB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                genreCB1MouseEntered(evt);
            }
        });
        genreCB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreCB1ActionPerformed(evt);
            }
        });

        newtitleTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newtitleTFKeyTyped(evt);
            }
        });

        publisherTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                publisherTFKeyTyped(evt);
            }
        });

        pagesTF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pagesTF1KeyTyped(evt);
            }
        });

        editionTF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editionTF1KeyTyped(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        authorName1TF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                authorName1TF1FocusLost(evt);
            }
        });
        authorName1TF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                authorName1TF1KeyTyped(evt);
            }
        });

        authorName2TF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                authorName2TF1FocusLost(evt);
            }
        });
        authorName2TF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                authorName2TF1KeyTyped(evt);
            }
        });

        authorName3TF1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                authorName3TF1FocusLost(evt);
            }
        });
        authorName3TF1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                authorName3TF1KeyTyped(evt);
            }
        });

        authorLbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        authorLbl1.setText("Author(s)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(authorLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(authorName3TF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(authorName2TF1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(authorName1TF1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorName1TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorName2TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorName3TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout newDefPanelLayout = new javax.swing.GroupLayout(newDefPanel);
        newDefPanel.setLayout(newDefPanelLayout);
        newDefPanelLayout.setHorizontalGroup(
            newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newDefPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newDefPanelLayout.createSequentialGroup()
                        .addComponent(titleStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(newtitleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(publisherStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(newDefPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editonStaticKbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genreStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pagesStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)))
                .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editionTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(publisherTF, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genreCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pagesTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        newDefPanelLayout.setVerticalGroup(
            newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newDefPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newtitleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(publisherStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(publisherTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titleStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(newDefPanelLayout.createSequentialGroup()
                        .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newDefPanelLayout.createSequentialGroup()
                                .addComponent(editionTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(genreCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pagesTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newDefPanelLayout.createSequentialGroup()
                                .addComponent(editonStaticKbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(genreStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pagesStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        modifyBTN.setFont(new java.awt.Font("JasmineUPC", 1, 24)); // NOI18N
        modifyBTN.setText("Modify Data");
        modifyBTN.setEnabled(false);
        modifyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBTNActionPerformed(evt);
            }
        });

        clearBTN1.setFont(new java.awt.Font("JasmineUPC", 1, 24)); // NOI18N
        clearBTN1.setText("Clear");
        clearBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(newDefPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(318, 318, 318))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bannerStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(accessionoStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(accessionnoTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(bookDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addComponent(bannerStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accessionoStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accessionnoTF1)
                    .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newDefPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(modifyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exitBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
        );

        jTabbedPane1.addTab("Modify Book", new javax.swing.ImageIcon(getClass().getResource("/images/modbook.png")), jInternalFrame2); // NOI18N

        jInternalFrame3.setTitle("Delete Book");
        jInternalFrame3.setVisible(true);

        bookList.setModel(new DefaultListModel());
        bookList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookListMouseClicked(evt);
            }
        });
        bookList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                bookListValueChanged(evt);
            }
        });
        ScrollPane.setViewportView(bookList);

        statusLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        editionLbl2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        genreLbl1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        publisherlbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        authorsLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        bookTitleLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        accessionnoLbl2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        accessionnoBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        accessionnoBannerLbl.setText("Accession No.");

        bookTitleBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bookTitleBannerLbl.setText("Book Title");

        authorsBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        authorsBannerLbl.setText("Authors");

        publisherBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        publisherBannerLbl.setText("Publisher");

        genreBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        genreBannerLbl.setText("Genre");

        editionBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editionBannerLbl.setText("Year");

        statusBannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        statusBannerLbl.setText("Status");

        issueBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        issueBTN.setText("Delete");
        issueBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                issueBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                issueBTNMouseExited(evt);
            }
        });
        issueBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBTNActionPerformed(evt);
            }
        });

        exitBTN2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitBTN2.setText("Exit");
        exitBTN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBTN2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBTN2MouseExited(evt);
            }
        });
        exitBTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTN2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Select book to delete");

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap(401, Short.MAX_VALUE)
                .addComponent(publisherlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame3Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jInternalFrame3Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(editionBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(statusBannerLbl)
                                .addComponent(genreBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(authorsBannerLbl)
                                    .addComponent(publisherBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accessionnoBannerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(bookTitleBannerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(29, 29, 29)
                            .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(accessionnoLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bookTitleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(authorsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                                .addComponent(editionLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(genreLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jInternalFrame3Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(exitBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(119, 119, 119)
                            .addComponent(issueBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(37, Short.MAX_VALUE)))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202)
                .addComponent(publisherlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame3Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jInternalFrame3Layout.createSequentialGroup()
                            .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(accessionnoLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bookTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11)
                                    .addComponent(authorsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accessionnoBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bookTitleBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(authorsBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(publisherBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                    .addComponent(genreLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(editionLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(statusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(genreBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(editionBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(statusBannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(42, 42, 42)
                            .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(issueBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(exitBTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                            .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)))
                    .addGap(46, 46, 46)))
        );

        jTabbedPane1.addTab("Delete Book", new javax.swing.ImageIcon(getClass().getResource("/images/subBook.png")), jInternalFrame3); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        accessionnoTF.setText(null);
        titleTF.setText(null);
        authorName1TF.setText(null);
        authorName2TF.setText(null);
        authorName3TF.setText(null);
        priceTF.setText(null);
        publisherCityTF.setText(null);
        publisherCountryTF.setText(null);
        publisherPhoneNoTF.setText(null);
        publisherNameTF.setText(null);
        editionTF.setText(null);
        pagesTF.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBTNActionPerformed

    private void genreCBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genreCBMouseEntered
        //TODO add your handling code here:
    }//GEN-LAST:event_genreCBMouseEntered

    private void genreCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreCBActionPerformed

    private void accessionnoTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accessionnoTFFocusLost

    }//GEN-LAST:event_accessionnoTFFocusLost

    private void accessionnoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accessionnoTFKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_accessionnoTFKeyTyped

    private void editionTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editionTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_editionTFKeyTyped

    private void titleTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTFKeyTyped

    private void pagesTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagesTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pagesTFKeyTyped

    private void publisherCityTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_publisherCityTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherCityTFKeyTyped

    private void publisherCountryTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_publisherCountryTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherCountryTFKeyTyped

    private void publisherPhoneNoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_publisherPhoneNoTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherPhoneNoTFKeyTyped

    private void publisherNameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_publisherNameTFFocusLost
        String query;
        try {
            query = "SELECT * FROM publisher where pub_Name='"+publisherNameTF.getText()+"';";
            System.out.println(query);
            rs = stmt.executeQuery(query);
            if(Utility.rs.next()) {
                System.out.println("Yes");
                String publisherID = Utility.rs.getString("pub_ID");
                String publisherCity = Utility.rs.getString("pub_city");
                String publisherCountry = Utility.rs.getString("pub_country");
                long publisherContactNo = Utility.rs.getLong("pub_contact_no");
                publisherCityTF.setText(publisherCity);
                publisherCountryTF.setText(publisherCountry);
                publisherPhoneNoTF.setText(String.valueOf(publisherContactNo));
                publisherCityTF.setEditable(false);
                publisherCountryTF.setEditable(false);
                publisherPhoneNoTF.setEditable(false);
                boolean idAlreayPresent = true;
            }
            else {
                query = "SELECT pub_ID FROM publisher;";
                rs = stmt.executeQuery(query);
                rs.afterLast();
                rs.previous();
                String id = rs.getString("pub_ID");
                int temp = Integer.parseInt(id.substring(3));
                temp++;
                String publisherID = "PUB".concat(String.valueOf(temp));
                boolean idAlreayPresent = false;
                publisherCityTF.setEditable(true);
                publisherCountryTF.setEditable(true);
                publisherPhoneNoTF.setEditable(true);
                publisherCityTF.setText(null);
                publisherCountryTF.setText(null);
                publisherPhoneNoTF.setText(null);

            }
        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_publisherNameTFFocusLost

    private void publisherNameTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_publisherNameTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherNameTFKeyTyped

    private void authorName1TFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_authorName1TFFocusLost

    }//GEN-LAST:event_authorName1TFFocusLost

    private void authorName1TFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorName1TFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_authorName1TFKeyTyped

    private void authorName2TFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_authorName2TFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_authorName2TFFocusLost

    private void authorName2TFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorName2TFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_authorName2TFKeyTyped

    private void authorName3TFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_authorName3TFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_authorName3TFFocusLost

    private void authorName3TFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorName3TFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_authorName3TFKeyTyped

    private void priceTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTFKeyTyped

    private void addBookBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookBTNActionPerformed
        try {
            int accesionNo = Integer.parseInt(accessionnoTF.getText());
            String title = titleTF.getText();
            String publisherName = publisherNameTF.getText();
            String authors[] ={authorName1TF.getText(),authorName2TF.getText(),authorName3TF.getText()};
            String edition = editionTF.getText();
            int pages = Integer.parseInt(pagesTF.getText());
            String genre = (String)genreCB.getSelectedItem();
            float price = Float.parseFloat(priceTF.getText());
            try {

                String query = "Insert into book_rec"+ " values(" +accesionNo + ",'" + title + "','" + authors[0] + "','" + authors[1] + "','"
                + authors[2]+ "','"+publisherID+"','"+genre+"','"+pages+"','"+price+"','"+edition+"','Unissued');";

                if(idAlreayPresent==false)
                {
                    publisherCity = publisherCityTF.getText();
                    publisherCountry = publisherCountryTF.getText();
                    publisherContactNo = Long.parseLong(publisherPhoneNoTF.getText());
                    String query2 = "INSERT INTO publisher values('"+publisherID+"','"+publisherName+"','"+publisherCity+"','"+publisherCountry+"',"+publisherContactNo+");";
                    stmt.executeUpdate(query2);

                }
                stmt.executeUpdate(query);
                System.out.println(query);

                clearBTN.doClick();
                JOptionPane.showMessageDialog(null, "Book Added");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }
        catch (Exception ep) {
            JOptionPane.showMessageDialog(this, "Plz check the Data you Entered");
        }

    }//GEN-LAST:event_addBookBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_exitBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        try {
            if(JOptionPane.showConfirmDialog(this,"Sure you want to delete this book ","Confirmation",JOptionPane.YES_NO_OPTION)==0)
            {            String query = "Delete from book_rec where Acc_No=" + accessionnoLbl.getText() + ";";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog (null,"Book Deleted");
                clearBTN.doClick();
            }
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"The Book issued to somebody", "Error",ERROR_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void accessionnoTF1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accessionnoTF1KeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_accessionnoTF1KeyTyped

    private void exitBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTN1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTN1ActionPerformed

    private void searchBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBTNMouseEntered

    private void searchBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBTNMouseExited

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        try {
            String query = "select A.*,B.pub_name from book_rec A,publisher b where A.Acc_NO=" + accessionnoTF.getText() + ";";
            rs = Utility.stmt.executeQuery(query);
            while (rs.next()) {
                accessionnoLbl.setText(rs.getInt("Acc_No") + "");
                editionLbl.setText(rs.getInt("Edition") + "");
                nameLbl.setText(rs.getString("Title"));
                publishernameLbl.setText(rs.getString("Pub_name"));

            }
            if(accessionnoLbl.getText().isEmpty())
            {
                modifyBTN.setEnabled(false);
                deleteBTN.setEnabled(false);
            }
            else
            {
                modifyBTN.setEnabled(true);
                deleteBTN.setEnabled(true);

            }
        } catch (Exception ep) {
            JOptionPane.showMessageDialog(this, "The Accession No you entered is not valid");
            modifyBTN.setEnabled(false);
            deleteBTN.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBTNActionPerformed

    private void genreCB1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genreCB1MouseEntered
        //TODO add your handling code here:
    }//GEN-LAST:event_genreCB1MouseEntered

    private void genreCB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreCB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreCB1ActionPerformed

    private void newtitleTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newtitleTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_newtitleTFKeyTyped

    private void publisherTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_publisherTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherTFKeyTyped

    private void pagesTF1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pagesTF1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pagesTF1KeyTyped

    private void editionTF1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editionTF1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_editionTF1KeyTyped

    private void authorName1TF1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_authorName1TF1FocusLost

    }//GEN-LAST:event_authorName1TF1FocusLost

    private void authorName1TF1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorName1TF1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_authorName1TF1KeyTyped

    private void authorName2TF1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_authorName2TF1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_authorName2TF1FocusLost

    private void authorName2TF1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorName2TF1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_authorName2TF1KeyTyped

    private void authorName3TF1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_authorName3TF1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_authorName3TF1FocusLost

    private void authorName3TF1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorName3TF1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_authorName3TF1KeyTyped

    private void modifyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBTNActionPerformed

        try
        {
            int accessionNo =Integer.parseInt(accessionnoLbl.getText());
            String   title =newtitleTF.getText();
            String publisher =publisherTF.getText();
            String author3,author2,author1 =authorName1TF.getText();
            author2 =authorName2TF.getText();
            author3 =authorName3TF.getText();
            String edition = editionTF.getText();
            int pages = Integer.parseInt(pagesTF.getText());
            String genre = (String)genreCB.getSelectedItem();
            try{
             //   String query="Update book_rec SET Title='"+title+"',Author1='"+author1+"',Author2='"+author2+"',Author3='"+author3+"',Publisher='"+pub+"',Genre='"+genre+"',Pages="+pg+",Total_Copies="+cop+",year="+year+" Where Ac_No="+acNo+";";
              //  Utility.stmt.executeUpdate(query);
                JOptionPane.showMessageDialog (null,"Database Updated");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog (this, e.getMessage());
            }

        }
        catch(Exception ep)
        {
            JOptionPane.showMessageDialog (this,"Plz check the Data you Entered");
        }// TODO add your handling code here:
    }//GEN-LAST:event_modifyBTNActionPerformed

    private void clearBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTN1ActionPerformed
        accessionnoTF.setText(null);
        nameLbl.setText(null);
        publishernameLbl.setText(null);
        accessionnoLbl.setText(null);
        editionLbl.setText(null);
        deleteBTN.setEnabled(false);
        modifyBTN.setEnabled(false);
        errorLabel.setText(null);     // TODO add your handling code here:
    }//GEN-LAST:event_clearBTN1ActionPerformed

    private void bookListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookListMouseClicked
        String value=(String)bookList.getSelectedValue();
        try
        {
            String query ="SELECT A.Acc_No,A.Title,A.Author1,A.Author2,A.Author3,B.Pub_name,A.genre,A.Edition,A.status,(SELECT count(Acc_NO) FROM book_rec where Title='"+value+"' and Status='Unissued') AS Copies_Left From book_rec A,publisher B where Title='"+value+"' and A.pub_ID=B.pub_ID Order by Title asc;";
            rs=Utility.stmt.executeQuery(query);
            while(rs.next())
            {
                int accessionNo = rs.getInt("Acc_No");
                String title  = rs.getString("Title");
                String authors ="<html>" + rs.getString("Author1").concat(" <br> ").concat(rs.getString("Author2")).concat(" <br> ").concat(rs.getString("Author3"));
                String publisher  = rs.getString("pub_name");
                String genre  = rs.getString("Genre");
                String edition  = rs.getString("Edition");
                String status = rs.getString("Copies_Left");
                accessionnoLbl.setText(accessionNo+"");
                authorsLbl.setText(authors);
                bookTitleLbl.setText(title);
                publisherlbl.setText(publisher);
                genreLbl1.setText("<html>"+genre);
                editionLbl.setText(edition);
                if(status.equals("0"))
                {
                    statusLbl.setText("No Copy Left");
                }
                else
                statusLbl.setText(status + " Copies Left");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bookListMouseClicked

    private void bookListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_bookListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_bookListValueChanged

    private void issueBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_issueBTNMouseEntered

    private void issueBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issueBTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_issueBTNMouseExited

    private void issueBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBTNActionPerformed

       

    }//GEN-LAST:event_issueBTNActionPerformed

    private void exitBTN2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTN2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTN2MouseEntered

    private void exitBTN2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTN2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTN2MouseExited

    private void exitBTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTN2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTN2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookManipulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookManipulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookManipulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookManipulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookManipulation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JLabel accessionnoBannerLbl;
    private javax.swing.JLabel accessionnoLbl;
    private javax.swing.JLabel accessionnoLbl1;
    private javax.swing.JLabel accessionnoLbl2;
    private javax.swing.JLabel accessionnoStaticLabel;
    private javax.swing.JTextField accessionnoTF;
    private javax.swing.JTextField accessionnoTF1;
    private javax.swing.JLabel accessionoStaticLbl;
    private javax.swing.JButton addBookBTN;
    private javax.swing.JLabel authorLbl;
    private javax.swing.JLabel authorLbl1;
    private javax.swing.JTextField authorName1TF;
    private javax.swing.JTextField authorName1TF1;
    private javax.swing.JTextField authorName2TF;
    private javax.swing.JTextField authorName2TF1;
    private javax.swing.JTextField authorName3TF;
    private javax.swing.JTextField authorName3TF1;
    private javax.swing.JLabel authorsBannerLbl;
    private javax.swing.JLabel authorsLbl;
    private javax.swing.JLabel bannerLBL;
    private javax.swing.JLabel bannerStaticLbl;
    private javax.swing.JPanel bookDetailPanel;
    private javax.swing.JList bookList;
    private javax.swing.JLabel bookTitleBannerLbl;
    private javax.swing.JLabel bookTitleLbl;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton clearBTN1;
    private javax.swing.JPanel componentPanel;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JLabel editionBannerLbl;
    private javax.swing.JLabel editionLbl;
    private javax.swing.JLabel editionLbl1;
    private javax.swing.JLabel editionLbl2;
    private javax.swing.JLabel editionStaticLbl;
    private javax.swing.JTextField editionTF;
    private javax.swing.JTextField editionTF1;
    private javax.swing.JLabel editonStaticKbl;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton exitBTN1;
    private javax.swing.JButton exitBTN2;
    private javax.swing.JLabel genreBannerLbl;
    private javax.swing.JComboBox genreCB;
    private javax.swing.JComboBox genreCB1;
    private javax.swing.JLabel genreLbl;
    private javax.swing.JLabel genreLbl1;
    private javax.swing.JLabel genreStaticLbl;
    private javax.swing.JButton issueBTN;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton modifyBTN;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel nameStaticLbl;
    private javax.swing.JPanel newDefPanel;
    private javax.swing.JTextField newtitleTF;
    private javax.swing.JLabel pagesLbl;
    private javax.swing.JLabel pagesStaticLbl;
    private javax.swing.JTextField pagesTF;
    private javax.swing.JTextField pagesTF1;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField priceTF;
    private javax.swing.JLabel publisherBannerLbl;
    private javax.swing.JLabel publisherCityLbl;
    private javax.swing.JTextField publisherCityTF;
    private javax.swing.JLabel publisherCountryLbl;
    private javax.swing.JTextField publisherCountryTF;
    private javax.swing.JLabel publisherNameLbl;
    private javax.swing.JTextField publisherNameTF;
    private javax.swing.JLabel publisherPhoneNoLbl;
    private javax.swing.JTextField publisherPhoneNoTF;
    private javax.swing.JLabel publisherStaticLbl;
    private javax.swing.JTextField publisherTF;
    private javax.swing.JLabel publisherlbl;
    private javax.swing.JLabel publishernameLbl;
    private javax.swing.JLabel publishernameStaticLbl;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel statusBannerLbl;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel titleStaticLbl;
    private javax.swing.JTextField titleTF;
    // End of variables declaration//GEN-END:variables
}
