/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sourceFiles;

import java.sql.SQLIntegrityConstraintViolationException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_CANCEL_OPTION;

/**
 *
 * @author Khati
 */
public class UserMenu extends javax.swing.JFrame {

    /**
     * Creates new form UserMenu
     */
    public UserMenu() {
        initComponents();
        Utility.centreWindow(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        pwdRetypeLBL = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();
        userNameLbl = new javax.swing.JLabel();
        phoneNoTF = new javax.swing.JTextField();
        addUserLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        pwdLBL = new javax.swing.JLabel();
        phonenoLbl = new javax.swing.JLabel();
        loginidLBL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTA = new javax.swing.JTextArea();
        addUserBTN = new javax.swing.JButton();
        useridTF = new javax.swing.JTextField();
        pwdPF = new javax.swing.JPasswordField();
        pwdRetypePF = new javax.swing.JPasswordField();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        bannerLbl = new javax.swing.JLabel();
        SP = new javax.swing.JScrollPane();
        userList = new javax.swing.JList();
        userIDLbl = new javax.swing.JLabel();
        userIDStaticLbl = new javax.swing.JLabel();
        userNameStaticLbl = new javax.swing.JLabel();
        userNameLbl1 = new javax.swing.JLabel();
        userPhonenoStaticLbl = new javax.swing.JLabel();
        userPhonenoLbl = new javax.swing.JLabel();
        userAddressLbl = new javax.swing.JLabel();
        userAddressStaticLbl = new javax.swing.JLabel();
        dateAndTimeStaticLbl = new javax.swing.JLabel();
        dateAndTimeLbl = new javax.swing.JLabel();
        deleteBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        accessionoStaticLbl = new javax.swing.JLabel();
        accessionnoTF = new javax.swing.JTextField();
        ExitBTN = new javax.swing.JButton();
        newDefPanel = new javax.swing.JPanel();
        titleStaticLbl = new javax.swing.JLabel();
        publisherStaticLbl = new javax.swing.JLabel();
        editonStaticKbl = new javax.swing.JLabel();
        newtitleTF = new javax.swing.JTextField();
        publisherTF = new javax.swing.JTextField();
        editionTF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressTA1 = new javax.swing.JTextArea();
        editonStaticKbl1 = new javax.swing.JLabel();
        ModifyBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UserMenu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jInternalFrame1.setTitle("Add User");
        jInternalFrame1.setVisible(true);

        pwdRetypeLBL.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        pwdRetypeLBL.setText("<html>Retype      <br>Password");

        userNameTF.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        userNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTFActionPerformed(evt);
            }
        });

        userNameLbl.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        userNameLbl.setText("User Name : ");

        phoneNoTF.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        phoneNoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoTFActionPerformed(evt);
            }
        });

        addUserLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addUserLbl.setText("<html> <center><font size =6><b>Add new User</b></font></center>");

        addressLbl.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        addressLbl.setText("Address     : ");

        pwdLBL.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        pwdLBL.setText("Password   :");

        phonenoLbl.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        phonenoLbl.setText("Phone no   : ");

        loginidLBL.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        loginidLBL.setText("User ID      : ");

        addressTA.setColumns(20);
        addressTA.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        addressTA.setLineWrap(true);
        addressTA.setRows(5);
        addressTA.setWrapStyleWord(true);
        jScrollPane1.setViewportView(addressTA);

        addUserBTN.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        addUserBTN.setText("Add User");
        addUserBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBTNActionPerformed(evt);
            }
        });

        useridTF.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        useridTF.setEnabled(false);
        useridTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridTFActionPerformed(evt);
            }
        });

        pwdPF.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        pwdPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPFActionPerformed(evt);
            }
        });

        pwdRetypePF.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pwdLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pwdRetypeLBL)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(phonenoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addressLbl))
                                    .addGap(8, 8, 8)))
                            .addGap(14, 14, 14)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(phoneNoTF)
                                .addComponent(jScrollPane1)
                                .addComponent(pwdPF)
                                .addComponent(pwdRetypePF, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(loginidLBL, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userNameLbl, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(18, 18, 18)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userNameTF)
                                .addComponent(useridTF, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(addUserLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(addUserBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addUserLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(loginidLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(useridTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(phonenoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(pwdLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pwdPF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwdRetypePF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdRetypeLBL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(addUserBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add User", new javax.swing.ImageIcon(getClass().getResource("/images/log.png")), jInternalFrame1); // NOI18N

        jInternalFrame3.setTitle("Delete User");
        jInternalFrame3.setVisible(true);

        bannerLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bannerLbl.setText("Select A User From List.........");

        userList.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        userList.setModel(new DefaultListModel());
        userList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userListMouseClicked(evt);
            }
        });
        userList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                userListValueChanged(evt);
            }
        });
        SP.setViewportView(userList);

        userIDLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        userIDLbl.setAlignmentX(0.5F);
        userIDLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        userIDStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        userIDStaticLbl.setText("User ID");

        userNameStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        userNameStaticLbl.setText("User Name");

        userNameLbl1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        userNameLbl1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        userPhonenoStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        userPhonenoStaticLbl.setText("User Phone no");

        userPhonenoLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        userPhonenoLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        userAddressLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        userAddressLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        userAddressStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        userAddressStaticLbl.setText("User Address");

        dateAndTimeStaticLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        dateAndTimeStaticLbl.setText("<html>Date & Time User Added");

        dateAndTimeLbl.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        dateAndTimeLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 204), null));

        deleteBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteBTN.setText("Delete");
        deleteBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBTNMouseExited(evt);
            }
        });
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        exitBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBTNMouseExited(evt);
            }
        });
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(bannerLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                        .addGap(192, 192, 192))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userNameStaticLbl)
                                    .addComponent(userIDStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userNameLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userIDLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(userPhonenoStaticLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userAddressStaticLbl)
                                    .addComponent(dateAndTimeStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userPhonenoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userAddressLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateAndTimeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(bannerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userIDStaticLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userNameStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userPhonenoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userPhonenoStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userAddressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userAddressStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateAndTimeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateAndTimeStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("Delete User", new javax.swing.ImageIcon(getClass().getResource("/images/log.png")), jInternalFrame3); // NOI18N

        jInternalFrame2.setTitle("Modify Details");
        jInternalFrame2.setVisible(true);

        accessionoStaticLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        accessionoStaticLbl.setText("User ID :");

        accessionnoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                accessionnoTFKeyTyped(evt);
            }
        });

        ExitBTN.setText("Exit");
        ExitBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBTNMouseExited(evt);
            }
        });
        ExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTNActionPerformed(evt);
            }
        });

        newDefPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true), "New Definations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N

        titleStaticLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        titleStaticLbl.setText("User ID :");

        publisherStaticLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        publisherStaticLbl.setText("User Name :");

        editonStaticKbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editonStaticKbl.setText("Phone No :");

        newtitleTF.setEnabled(false);
        newtitleTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newtitleTFKeyTyped(evt);
            }
        });

        publisherTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                publisherTFKeyTyped(evt);
            }
        });

        editionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editionTFActionPerformed(evt);
            }
        });
        editionTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editionTFKeyTyped(evt);
            }
        });

        addressTA1.setColumns(20);
        addressTA1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        addressTA1.setLineWrap(true);
        addressTA1.setRows(5);
        addressTA1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(addressTA1);

        editonStaticKbl1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        editonStaticKbl1.setText("Address   :");

        javax.swing.GroupLayout newDefPanelLayout = new javax.swing.GroupLayout(newDefPanel);
        newDefPanel.setLayout(newDefPanelLayout);
        newDefPanelLayout.setHorizontalGroup(
            newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newDefPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newDefPanelLayout.createSequentialGroup()
                        .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleStaticLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(newDefPanelLayout.createSequentialGroup()
                                .addComponent(publisherStaticLbl)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(21, 21, 21)
                        .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newtitleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publisherTF, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(262, 262, 262))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newDefPanelLayout.createSequentialGroup()
                        .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(newDefPanelLayout.createSequentialGroup()
                                .addComponent(editonStaticKbl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editionTF))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newDefPanelLayout.createSequentialGroup()
                                .addComponent(editonStaticKbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2)))
                        .addGap(253, 253, 253))))
        );
        newDefPanelLayout.setVerticalGroup(
            newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newDefPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newDefPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(publisherTF, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(publisherStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(newtitleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editonStaticKbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editionTF, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newDefPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newDefPanelLayout.createSequentialGroup()
                        .addComponent(editonStaticKbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(183, 183, 183))
                    .addGroup(newDefPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        ModifyBTN.setText("Modify");
        ModifyBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ModifyBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModifyBTNMouseExited(evt);
            }
        });
        ModifyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyBTNActionPerformed(evt);
            }
        });

        searchBTN.setText("Search In Library Database ");
        searchBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchBTNMouseExited(evt);
            }
        });
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });

        clearBTN.setText("Clear");
        clearBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBTNMouseExited(evt);
            }
        });
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addComponent(newDefPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addGap(2, 32, Short.MAX_VALUE)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(ExitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ModifyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(accessionoStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accessionnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accessionnoTF, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accessionoStaticLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(newDefPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("Modify User", new javax.swing.ImageIcon(getClass().getResource("/images/log.png")), jInternalFrame2); // NOI18N

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel4.setText("WestSide Library Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTFActionPerformed

    private void phoneNoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoTFActionPerformed

    private void addUserBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBTNActionPerformed
        String epwd=null,query,username,userid,address;
        long phoneno;
        try {
            address = addressTA.getText();
            phoneno = Long.parseLong(phoneNoTF.getText());
            userid= useridTF.getText();
            username = userNameTF.getText();
            if(!(new String(pwdPF.getPassword()).equals(new String(pwdRetypePF.getPassword()))))
            {
                JOptionPane.showMessageDialog(this,"Password Do Not Match", "Error",ERROR_MESSAGE);
                pwdPF.setText(null);
                pwdRetypePF.setText(null);
                pwdPF.requestFocus();
            }
            else{
                epwd = new Utility().encrypt(new String(pwdPF.getPassword()));
                query = "INSERT INTO user VALUES('"+userid+"','"+username+"','"+epwd+"','"+Utility.getCurrentDate()+"','"+Utility.getCurrentTime()+"',"+phoneno+",'"+address+"');";
                Utility.stmt.executeUpdate(query);
                if( JOptionPane.showConfirmDialog(this,"User ID : " + useridTF.getText()+" added,Wanna Add More ?","Sucess",JOptionPane.YES_NO_OPTION)==0)
                {
                    formWindowOpened(null);
                    userNameTF.setText(null);
                    addressTA.setText(null);
                    phoneNoTF.setText(null);
                    pwdPF.setText(null);
                    pwdRetypePF.setText(null);
                    userNameTF.requestFocus();
                }
                else
                dispose();
            }
        }
        catch(SQLIntegrityConstraintViolationException eq)
        {
            JOptionPane.showMessageDialog(this,"User ID Not Avalable","ID Error",ERROR_MESSAGE);
            useridTF.setText(null);
            useridTF.requestFocus();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }

    }//GEN-LAST:event_addUserBTNActionPerformed

    private void useridTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_useridTFActionPerformed

    private void pwdPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdPFActionPerformed

    private void userListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userListMouseClicked
        if(!(userList.getSelectedValue()==null))
        {
            try
            {
                String query= "SELECT * FROM user where User_name = '"+userList.getSelectedValue()+"';";
                Utility.rs=Utility.stmt.executeQuery(query);
                Utility.rs.first();
                userIDLbl.setText(Utility.rs.getString("User_ID"));
                userNameLbl1.setText(Utility.rs.getString("User_Name"));
                userPhonenoLbl.setText(Utility.rs.getLong("User_Phoneno")+"");
                userAddressLbl.setText("<html>"+Utility.rs.getString("Issuer_Address"));
                dateAndTimeLbl.setText(Utility.rs.getDate("Date_User_Added")+" , "+Utility.rs.getString("Time_User_Added"));
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e.toString());
            }
        }
        else
        JOptionPane.showMessageDialog(this,"No User to display");
    }//GEN-LAST:event_userListMouseClicked

    private void userListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_userListValueChanged
        // TODO add yo handling code here:
    }//GEN-LAST:event_userListValueChanged

    private void deleteBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBTNMouseEntered

    private void deleteBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBTNMouseExited

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        try
        {
            if(JOptionPane.showConfirmDialog(this,"Are you Sure to delete "+userNameLbl.getText()+" ?","Delete Confirm", YES_NO_CANCEL_OPTION)==0)
            {
                String query ="DELETE from user where user_id='"+userIDLbl.getText()+"'";
                Utility.stmt.executeUpdate(query);
                formWindowOpened(null);
                userIDLbl.setText(null);
                userAddressLbl.setText(null);
                userNameLbl.setText(null);
                userPhonenoLbl.setText(null);
                dateAndTimeLbl.setText(null);
                JOptionPane.showMessageDialog(this,"User has been Deleted","Deletion Done",INFORMATION_MESSAGE);
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void exitBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTNMouseEntered

    private void exitBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTNMouseExited

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTNActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
sourceFiles.Utility.initialize();
        DefaultListModel lm = (DefaultListModel) userList.getModel();
        lm.removeAllElements();
        try
{
      String query ="SELECT User_name From user Order By User_name desc;";
       Utility.rs=Utility.stmt.executeQuery(query);
       while(Utility.rs.next())
       {
       String tit  = Utility.rs.getString("User_name");
       lm.add(0,tit);
       userList.setModel(lm);
       }
}
catch (Exception e)
     {
       JOptionPane.showMessageDialog(this, e.getMessage());
     }      
try
{       useridTF.setText(Utility.getUserID());
}
catch(Exception e)
{
    System.out.println(e.getMessage());
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void accessionnoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accessionnoTFKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_accessionnoTFKeyTyped

    private void ExitBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitBTNMouseEntered

    private void ExitBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitBTNMouseExited

    private void ExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTNActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitBTNActionPerformed

    private void newtitleTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newtitleTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_newtitleTFKeyTyped

    private void publisherTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_publisherTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_publisherTFKeyTyped

    private void editionTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editionTFKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_editionTFKeyTyped

    private void editionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editionTFActionPerformed

    private void ModifyBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyBTNMouseEntered

    private void ModifyBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyBTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyBTNMouseExited

    private void ModifyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyBTNActionPerformed

    private void searchBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBTNMouseEntered

    private void searchBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBTNMouseExited

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBTNActionPerformed

    private void clearBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBTNMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBTNMouseEntered

    private void clearBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBTNMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBTNMouseExited

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBTN;
    private javax.swing.JButton ModifyBTN;
    private javax.swing.JScrollPane SP;
    private javax.swing.JTextField accessionnoTF;
    private javax.swing.JLabel accessionoStaticLbl;
    private javax.swing.JButton addUserBTN;
    private javax.swing.JLabel addUserLbl;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextArea addressTA;
    private javax.swing.JTextArea addressTA1;
    private javax.swing.JLabel bannerLbl;
    private javax.swing.JButton clearBTN;
    private javax.swing.JLabel dateAndTimeLbl;
    private javax.swing.JLabel dateAndTimeStaticLbl;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JTextField editionTF;
    private javax.swing.JLabel editonStaticKbl;
    private javax.swing.JLabel editonStaticKbl1;
    private javax.swing.JButton exitBTN;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel loginidLBL;
    private javax.swing.JPanel newDefPanel;
    private javax.swing.JTextField newtitleTF;
    private javax.swing.JTextField phoneNoTF;
    private javax.swing.JLabel phonenoLbl;
    private javax.swing.JLabel publisherStaticLbl;
    private javax.swing.JTextField publisherTF;
    private javax.swing.JLabel pwdLBL;
    private javax.swing.JPasswordField pwdPF;
    private javax.swing.JLabel pwdRetypeLBL;
    private javax.swing.JPasswordField pwdRetypePF;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel titleStaticLbl;
    private javax.swing.JLabel userAddressLbl;
    private javax.swing.JLabel userAddressStaticLbl;
    private javax.swing.JLabel userIDLbl;
    private javax.swing.JLabel userIDStaticLbl;
    private javax.swing.JList userList;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JLabel userNameLbl1;
    private javax.swing.JLabel userNameStaticLbl;
    private javax.swing.JTextField userNameTF;
    private javax.swing.JLabel userPhonenoLbl;
    private javax.swing.JLabel userPhonenoStaticLbl;
    private javax.swing.JTextField useridTF;
    // End of variables declaration//GEN-END:variables
}
